# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

sudo: false # route your build to the container-based infrastructure for a faster build
language: java
install: true
jdk:
  - openjdk8

env:
  global:
    - secure: "Nvz5Pjjg+FJ9Aly4ZiDZU7dC6Mo1r0SwE/fYVD43I57IWSgT0Z9PTpOZtDxllmjpkd6rJzw4Yxkh4iVhvYRv1VjohOA2ofIT0Fv6nJPVqixUUixv5y/x+vuOxs8q2zzMhUEqjzjVdlF9SO8nm2KOSDOvTqqAGWTwIv0dzlEPzxyGVTQO3/yxV/k0MQ4CSYsjVu4Gvcm5PovOFMPc8Rxfg6OP40eDpVwkJOFuvCvK8hE9p7em2Ww4ADvt2eEVWbjeIRuAATMLNWPvv5tmUgGFJkpj1x99MIwYqGUU1E8QUpA2Ezu0X/Fz8rsS+TeZLbqKZVgw6udk7dX0R5YE190T96r1vUyNDGSGGtZYxuxJo93/Gsm+rVWbsrg8E+7RKTuAwL0zAtv501knKgo2wPOCtaiLjhkiixA8X95ygbBC0BueYYNszSMpWgyv8ltCo+oyGq2WLQlelyVzzLuHVdPzl2aUr6Kn/9Jig3HmIq//p8UCqKzOp8/rO5JLhodjfYX8pNn/FSVNdPFRsYvTNHsw1YhScC7T2GwlZ0c+ElxlHjqp20epBWGU8lS54Qfm7rx/r4Q17l+yQfREUnmd+vSgVd1F3r6HTgTQF1q6M+0jk6Jw7kFu6pVdudcIxdadgXTrXpguEFhwtzDtgZlJ5RqgqR9Ne84rCMxJuyQPPuZTx9M="
    - secure: "OAChPB92T2OQ1V28zwB3S0mic+ebmxHRZvue/uCP2Hl/A40b+5xOvhVcdTR3onywQXm0wXXlpE6TCNoIMgt0uWZ2v8a3KhOQE5VudCB8fV169o17Rm8Yn03Ke1qZfL4jelxAJjipaUZimk+yJeI2P+z/g4RtiY8xNS5GOL9cyW1TMfnf8WVlf5oqT8CF8ytjC+L7L5F947j5M537R2nDiDa5UysgCw41HrBvIzTaqjCbBRsNTH7/z/T4z1Otewx/pn28unN3MWUDbtwh306TK+M/2ndApEzahZ5y2sNupamkswGiDxW9DMuH2IenfbAyuIx/JlYEbJDarVzt/BZJeSGwCTygy0H5VNc2eVSkIL4aD6yW4zsU7LjkASk2sLmUVSyBcaWO4Bf7+8zT5MJC5BCQCl7KY1XTtF53VrFi1rEd5pt2ttukPi+3KzjzS42ia7TtMLZ3ZBNSzz/jkqNkHmb09G7TgEsqFqrBVYW1VnNZBLaO7VQ9sA4BxMBhs+ToXoPODN48r2tFnGFvzqPV3BJ1Nm8d4g3jKuCqX+1qxn5UgmbIKJKRBCsdj1CD0+yXf6SYXkeqMVx7zRpIy+sz1VFYvSFd5CdDZ0uQSQQh4+LmY9P9KeLP+hL7lwgUn+Jtct5bn/nU+S9WhbYQWOgPzgMI+jUj9etQpQa/bLZHXcM="

before_install:
  - openssl aes-256-cbc -K $encrypted_5354643beb17_key -iv $encrypted_5354643beb17_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

script:
  - ./mvnw clean install -X -Djarsigner.skip=false checkstyle:check

after_success:
  - ./mvnw test jacoco:report coveralls:report

deploy:
  - provider: script
    script: ./mvnw -s ci-settings.xml deploy -X checkstyle:checkstyle
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "Urr6TRCCgbNF6uxeRwLieAUmpGdYNlXntnNt3T0Q3T5//mWA+61Il6znZMefETnmTdSEQiDhK8YM7F5K2oeNkVIVUratNdFS/wvtxzOMuXEWhmUGOlXyPXxKx5daHVq/CtTbdkIhDJPY9TnJwg/QzzG0LBscCpJf1VHqOkV+kic5I7LMxXHjofIKaqBFu999DRO4fwH0626hIztCghMPXDR6LCUYQSqvL49YI8KMX1tjLYpcXbubD5CkQcWXGPYTDgqM8Dh1/4Pk2tNdmvOwqbY53FY3DeKXW4bdQO/A17MffF2i2UqRzn1uEvEFtHhPZ1v6M8BWrXutOxKjY7VZFS6IYcWzFntfwv9cEvtNyfJzTykvVpIdUw4EIxCLz2tjXIHyPfvPwZsehVBQ7VzhvpZ6NxO15YS6mrmkVHBu52/qf/+pBJzQn5X0CxBQKg94n1dl7k1bhkTOaBGLOnngib+0MwiYU+FLkot24oFdXDUYtvQ6mmXUa5TRVSW3rDBrTkQTi5HPSzp02yDbqNimIuUBMu11bMEXVbpklZsWNfln/UUPmFDD6EzN42ZIbQreHqbw8NEkiv47Fm4TPhb0Mp0yI/FuOB9+U+ZTk1W7Y6xMQi+UiCFb1i8cr7mfqqpWsvYZFFsV0n79RdAOjaLhru86TTbtYNOZCJGIlPES/PU="
    file_glob: true
    file:
      - "target/bkdf-*.jar"
      - "target/*.sha256"
      - "target/checksum-sha256.txt"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: "H9VHcG8NJL4RLDUkrcROCQZyCRUpZGdMelNtPLcndJ8GT1dc8TOWyU3aNZzfVFoeXSy63snZPUSeOHIld4+Ecga13E1CLNBKuKKNtqXSZQLD3n5J8j5WyktJBfqhsvgwnz3J7lDK4Vun328vzub44TwjlJI0JjBt04VzfOSj7XvSiENLOUEys6VIa8yy6n0+rLv3YF1KbrlgD4C9EVMK7ORQXW1iULEO6x92qsoQrd/G+KU6OprJOgKYAnr7LJ1x/hpt5FWW2rbFJMBMin7HNTc/g+jJp9rHZEUCOaJKwi8NfLj8bSlfenVaK27DXHF/5YsOyioGrTA089/6It2kZY1MmQf5sy5llmwY7pAgwketkLLq9MbOzRZer3OiZqaeYHSd5ttfq36lDmf8A2Nik1gmsloKD9zksv/YRrmfpczTBcNcBzi4C6zaa6KvkcuGJjKN655uxXwOD5YzN3IwRn0mEn5AN4PZRo7aTHjoCp9J0g50MZUSQZY0uAggz8nFr9aeB9vXr2d3w7aCWSide8dPFUHzfQUNXnKcfZveUwjp1Eh5SlZcO62npL9iuFgaGqtLeyoEQIdwhm4DaeTlQTnE6fQYNblWkNvxnBnXza3yiZipaK38f6fKiwGvJ4Jb9cTqpeiSE/bQ+rVKCXrcFvea6wYFqviy2wjczqyP7tE="
  email: false
